#- name: Install share mounts
# vars:
#   samba_share_path1: "//192.168.50.28/CarlShare"  # Samba share path (server IP and share name)
#   mount_point1: "/mnt/CarlShare"  # Local directory where the share will be mounted

#   samba_share_path2: "//192.168.50.28/Family"  # Samba share path (server IP and share name)
#   mount_point2: "/mnt/FamilyShare"  # Local directory where the share will be mounted

#   samba_share_path3: "//192.168.50.28/Media/"  # Samba share path (server IP and share name)
#   mount_point3: "/mnt/MediaShare"  # Local directory where the share will be mounted

#   samba_credentials: "/home/carl/.smbcredentials"
#   samba_user: "carl"  # Samba user name
#   samba_password: "CarlAccess0!"  # Samba user password
#   fstab_backup: "/etc/fstab.bak"  # Backup for fstab file

#  tasks:
- name: Ensure cifs-utils is installed
  ansible.builtin.apt:
    name: cifs-utils
    state: latest
# when: ansible_os_family == Debian

- name: Ensure samba-client is installed
  ansible.builtin.apt:
    name: samba-client
    state: latest
# when: ansible_os_family == "Debian"

- name: Ensure .smbcredentials file is installed
  copy: src=files/smbcredentials dest=/home/carl/.smbcredentials owner=carl group=carl mode=0744

- name: Create CarlShare mount point directory
  file:
    path: "//192.168.50.28/CarlShare"
    state: directory
    owner: carl
    group: users
    mode: '0755'

- name: Create FamilyShare mount point directory
  file:
    path: "//192.168.50.28/Family"
    state: directory
    owner: carl
    group: users
    mode: '0755'

- name: Create MediaShare mount point directory
  file:
    path: "//192.168.50.28/Media/"
    state: directory
    owner: carl
    group: users
    mode: '0755'

- name: Backup the /etc/fstab file
  copy:
    src: /etc/fstab
    dest: "/etc/fstab.bak"
    backup: yes

- name: Restart services
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Mount remoteShare
  ansible.posix.mount:
    path: /mnt/CarlShare
    src: //192.168.50.28/CarlShare
    fstype: cifs
    opts: "uid=carl,gid=users,credentials=/home/carl/.smbcredentials"
    state: mounted

- name: Mount FamilyShare
  ansible.posix.mount:
    path: /mnt/FamilyShare
    src: //192.168.50.28/Family
    fstype: cifs
    opts: "uid=carl,gid=users,credentials=/home/carl/.smbcredentials"
    state: mounted

- name: Mount MediaShare
  ansible.posix.mount:
    path: /mnt/MediaShare
    src: //192.168.50.28/Media
    fstype: cifs
    opts: "uid=carl,gid=users,credentials=/home/carl/.smbcredentials"
    state: mounted

