- name: Install apt packages
  ansible.builtin.apt:
    name: 
    - qemu-guest-agent
    - openssh-server
    - neovim
    - chromium
    - deja-dup
    state: latest

- name: Install flatpak packages
  community.general.flatpak:
    name: 
    - com.brave.Browser
    - org.freecad.FreeCAD
    state: present

