- name: Install apt packages
  ansible.builtin.apt:
    name: 
    - qemu-guest-agent
    - openssh-server
    - cifs-utils
    - samba-client
    - neovim
    - chromium
    - deja-dup
    state: latest

- name: Install flatpak packages
  community.general.flatpak:
    name: 
    - com.brave.Browser
    - org.freecad.FreeCAD
    state: latest

- name: Upgrade all flatpaks
  ansible.builtin.command: flatpak update --noninteractive
  register: flatpak_update_output
  changed_when: "'app/' in flatpak_update_output.stdout"      

